#!/usr/bin/env node

/**
 * setup-hooks.js
 * Installe le hook git post-commit pour synchroniser _dev.html.
 */

import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const ROOT = execSync("git rev-parse --show-toplevel", {
  encoding: "utf8",
}).trim();

const hookDir = path.join(ROOT, ".git", "hooks");
const hookPath = path.join(hookDir, "post-commit");

const hookContent = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.js
# Sync _dev.html after each local commit, then amend if needed.

npm run -s dev:sync -- --from-hook || true

# If _dev.html was modified by the sync, include it in the current commit.
if ! git diff --quiet _dev.html 2>/dev/null; then
  git add _dev.html
  git commit --amend --no-edit --no-verify -q
fi
`;

if (!fs.existsSync(hookDir)) {
  fs.mkdirSync(hookDir, { recursive: true });
}

fs.writeFileSync(hookPath, hookContent, "utf8");

try {
  fs.chmodSync(hookPath, 0o755);
} catch {
  // On Windows, chmod can be ignored safely.
}

console.log("[OK] Hook installé:", hookPath);
